// CallMethod 常量对象
export const CallMethod = {
  takeScreenshot: "takeScreenshot",
  overlayToast: "overlayToast",
  setNodeText: "setNodeText",
  findByTags: "findByTags",
  findById: "findById",
  findByText: "findByText",
  findByTextAllMatch: "findByTextAllMatch",
  containsText: "containsText",
  getAllText: "getAllText",
  findFirstParentByTags: "findFirstParentByTags",
  getAllNodes: "getAllNodes",
  getNodes: "getNodes",
  findFirstParentClickable: "findFirstParentClickable",
  getChildren: "getChildren",
  getBoundsInScreen: "getBoundsInScreen",
  isVisible: "isVisible",
  click: "click",
  longClick: "longClick",
  back: "back",
  home: "home",
  notifications: "notifications",
  recentApps: "recentApps",
  paste: "paste",
  focus: "focus",
  selectionText: "selectionText",
  scrollForward: "scrollForward",
  launchApp: "launchApp",
  getPackageName: "getPackageName",
  getScreenSize: "getScreenSize",
  getAppScreenSize: "getAppScreenSize",
  scrollBackward: "scrollBackward",
  setOverlayFlags: "setOverlayFlags",
  scanQR: "scanQR",
  loadWebViewOverlay: "loadWebViewOverlay",

  clickByGesture: "clickByGesture",
  clickNodeByGesture: "clickNodeByGesture",
  doubleClickNodeByGesture: "doubleClickNodeByGesture",
  performLinearGesture: "performLinearGesture",
  longPressGestureAutoPaste: "longPressGestureAutoPaste",

  getAppInfo: "getAppInfo",
  getMacAddress: "getMacAddress",
  getAndroidID: "getAndroidID",
  getUniqueDeviceId: "getUniqueDeviceId",

  addAccessibilityEventFilter: "addAccessibilityEventFilter",
  setAccessibilityEventFilters: "setAccessibilityEventFilters",

  httpRequest: "httpRequest",
  getDeviceInfo: "getDeviceInfo",
  getNetworkType: "getNetworkType",
  isAppInstalled: "isAppInstalled",
  getClipboardLatestText: "getClipboardLatestText",
} as const;

// 导出类型定义
export type CallMethodType = (typeof CallMethod)[keyof typeof CallMethod];
