// CallMethod 常量对象
export const CallMethod = {
    takeScreenshot: "takeScreenshot",
    overlayToast: "overlayToast",
    setNodeText: "setNodeText",
    findByTags: "findByTags",
    findById: "findById",
    findByText: "findByText",
    findByTextAllMatch: "findByTextAllMatch",
    containsText: "containsText",
    getAllText: "getAllText",
    findFirstParentByTags: "findFirstParentByTags",
    getAllNodes: "getAllNodes",
    getNodes: "getNodes",
    findFirstParentClickable: "findFirstParentClickable",
    getChildren: "getChildren",
    dispatchGesture: "dispatchGesture",
    getBoundsInScreen: "getBoundsInScreen",
    isVisible: "isVisible",
    click: "click",
    longClick: "longClick",
    gestureClick: "gestureClick",
    back: "back",
    home: "home",
    notifications: "notifications",
    recentApps: "recentApps",
    paste: "paste",
    selectionText: "selectionText",
    scrollForward: "scrollForward",
    launchApp: "launchApp",
    getPackageName: "getPackageName",
    getScreenSize: "getScreenSize",
    getAppScreenSize: "getAppScreenSize",
    nodeGestureClick: "nodeGestureClick",
    nodeGestureClickByDouble: "nodeGestureClickByDouble",
    scrollBackward: "scrollBackward",
    setOverlayFlags: "setOverlayFlags"
} as const;

// 导出类型定义
export type CallMethodType = typeof CallMethod[keyof typeof CallMethod]; 